export const ACTION_TYPE = {
  LOGOUT: "LOGOUT",
  ON_OPEN_MODAL: "ON_OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_USER: "SET_USER",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_UPDATE_USER: "SET_UPDATE_USER,",
  SET_USERS: "SET_USERS",
};
